name: gmt-python
channels:
    - conda-forge
    - conda-forge/label/dev
    - defaults
dependencies:
    - python=3.6
    - pip
    - gmt=6.0.0*
    - numpy
    - pandas
    - xarray
    - ipython
    - matplotlib
    - jupyter
    - pytest
    - pytest-cov
    - pytest-mpl
    - coverage
    - flake8
    - pylint
    - sphinx
    - sphinx_rtd_theme
    - nbsphinx
    - numpydoc
    - twine
