name: pygmt
channels:
    - conda-forge
    - nodefaults
dependencies:
    # Required dependencies
    - pip
    - gmt=6.1.1
    - numpy
    - pandas
    - xarray
    - netCDF4
    - packaging
    # Development dependencies
    - codecov
    - coverage[toml]
    - ipython
    - make
    - pytest-cov
    - pytest-mpl
    - pytest>=6.0
    - sphinx
    - sphinx-copybutton
    - sphinx-gallery
    - sphinx_rtd_theme=0.4.3
