name: gmt-python
channels:
    - conda-forge
dependencies:
    - python=3.6
    - pip
    - numpy
    - pandas
    - xarray
    - netCDF4
    - packaging
    - ipython
    - matplotlib
    - jupyter
    - pytest
    - pytest-cov
    - pytest-mpl
    - coverage
    - black
    - pylint
    - flake8
    - sphinx
    - sphinx_rtd_theme
    - nbsphinx
    - numpydoc
