name: pygmt
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.7
    - pip
    - numpy
    - pandas
    - xarray
    - netCDF4
    - packaging
    - ipython
    - matplotlib
    - jupyter
    - pytest
    - pytest-cov
    - pytest-mpl
    - coverage
    - black
    - pylint
    - flake8
    - sphinx<=1.8.5
    - sphinx_rtd_theme
    - sphinx-gallery
    - nbsphinx
    - numpydoc
