[tool.poetry]
name = "pygmt"
version = "0.3.1"
description = "A Python interface for the Generic Mapping Tools"
authors = ["The PyGMT Developers"]
license = "BSD License"

[tool.poetry.dependencies]
myst-parser = {version = "*", optional = true}
netCDF4 = "*"
numpy = "*"
packaging = "*"
pandas = "*"
python = "^3.7"
sphinx = {version = "*", optional = true}
sphinx-copybutton = {version = "*", optional = true}
sphinx-gallery = {version = "*", optional = true}
sphinx_rtd_theme = {version = "0.4.3", optional = true}
xarray = "*"

[tool.poetry.dev-dependencies]
black = "*"
blackdoc = "*"
codecov = "*"
coverage = {extras = ["toml"], version = "*"}
docformatter = "*"
flake8 = "*"
ipython = "*"
isort = ">=5"
jupyter = "*"
make = "*"
matplotlib = "*"
pylint = "*"
pytest-cov = "*"
pytest-mpl = "*"
pytest = ">=6.0"

[tool.poetry.extras]
docs = ["myst-parser", "sphinx", "sphinx-copybutton", "sphinx-gallery", "sphinx_rtd_theme"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.run]
omit = ["*/tests/*", "*pygmt/__init__.py"]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--verbose --durations=0 --durations-min=0.2 --doctest-modules --mpl --mpl-results-path=results"

[tool.isort]
profile = "black"
skip_gitignore = true
known_third_party = "pygmt"
