# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Schedule daily tests
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    name: ${{ matrix.os }} - Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8]
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      # Checkout current git repository
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          # fecth all history so that versioneer works
          fetch-depth: 0

      # Setup Miniconda
      - name: Setup Miniconda
        uses: goanpeca/setup-miniconda@v1.6.0
        with:
          python-version: ${{ matrix.python-version }}
          channels: conda-forge

      # Install GMT and other required dependencies from conda-forge
      - name: Install GMT and required dependencies
        shell: bash -l {0}
        run: |
          requirements_file=full-conda-requirements.txt
          cat requirements.txt requirements-dev.txt > $requirements_file
          cat << EOF >> $requirements_file
          gmt=6.0.0
          make
          EOF
          conda install --yes --file $requirements_file

      # Show installed pkg information for postmortem diagnostic
      - name: List installed packages
        shell: bash -l {0}
        run: conda list

      # Cache the ${HOME}/.gmt directory, for docs and testing
      - name: Cache GMT directory
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            ~/.gmt/cache
            ~/.gmt/server
          key: cache-gmt-${{ github.ref }}-${{ runner.os }}-20200609
          restore-keys: cache-gmt-refs/heads/master-

      # Workaround for the timeouts of 'gmt which' on Linux and Windows
      - name: Download remote data using wget (Linux & Windows)
        shell: bash -l {0}
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then choco install wget; fi  # install wget on Windows
          mkdir ~/.gmt ~/.gmt/cache ~/.gmt/server
          wget --no-check-certificate https://oceania.generic-mapping-tools.org/gmt_hash_server.txt -P ~/.gmt/server/
          for data in earth_relief_01d.grd earth_relief_30m.grd earth_relief_10m.grd; do
            wget --no-check-certificate https://oceania.generic-mapping-tools.org/${data} -P ~/.gmt/server/
          done
          for data in ridge.txt Table_5_11.txt tut_bathy.nc tut_quakes.ngdc tut_ship.xyz usgs_quakes_22.txt; do
            wget --no-check-certificate https://oceania.generic-mapping-tools.org/cache/${data} -P ~/.gmt/cache/
          done
        if: steps.cache.outputs.cache-hit != 'true' && runner.os != 'macOS'

      # Download remote files, if not already cached
      - name: Download remote data (macOS)
        shell: bash -l {0}
        run: gmt which -Gu @earth_relief_01d @earth_relief_30m @earth_relief_10m @ridge.txt @Table_5_11.txt @tut_bathy.nc @tut_quakes.ngdc @tut_ship.xyz @usgs_quakes_22.txt
        if: steps.cache.outputs.cache-hit != 'true' && runner.os == 'macOS'

      # Install the package that we want to test
      - name: Install the package
        shell: bash -l {0}
        run: |
          python setup.py sdist --formats=zip
          pip install dist/*

      # Run the tests
      - name: Test with pytest
        shell: bash -l {0}
        run: make test PYTEST_EXTRA="-r P"
